/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSubdomainRouteImport } from './routes/products.$subdomain'
import { Route as PSubdomainRouteImport } from './routes/p.$subdomain'
import { Route as AdminSubdomainsRouteImport } from './routes/admin.subdomains'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCountriesRouteImport } from './routes/admin.countries'
import { Route as PSubdomainIndexRouteImport } from './routes/p.$subdomain.index'
import { Route as PSubdomainCountryRouteImport } from './routes/p.$subdomain.$country'

const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSubdomainRoute = ProductsSubdomainRouteImport.update({
  id: '/products/$subdomain',
  path: '/products/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const PSubdomainRoute = PSubdomainRouteImport.update({
  id: '/p/$subdomain',
  path: '/p/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubdomainsRoute = AdminSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AdminRoute,
} as any)
const PSubdomainIndexRoute = PSubdomainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PSubdomainRoute,
} as any)
const PSubdomainCountryRoute = PSubdomainCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => PSubdomainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/track': typeof TrackRoute
  '/upsell': typeof UpsellRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subdomains': typeof AdminSubdomainsRoute
  '/p/$subdomain': typeof PSubdomainRouteWithChildren
  '/products/$subdomain': typeof ProductsSubdomainRoute
  '/admin/': typeof AdminIndexRoute
  '/p/$subdomain/$country': typeof PSubdomainCountryRoute
  '/p/$subdomain/': typeof PSubdomainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/track': typeof TrackRoute
  '/upsell': typeof UpsellRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subdomains': typeof AdminSubdomainsRoute
  '/products/$subdomain': typeof ProductsSubdomainRoute
  '/admin': typeof AdminIndexRoute
  '/p/$subdomain/$country': typeof PSubdomainCountryRoute
  '/p/$subdomain': typeof PSubdomainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/track': typeof TrackRoute
  '/upsell': typeof UpsellRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subdomains': typeof AdminSubdomainsRoute
  '/p/$subdomain': typeof PSubdomainRouteWithChildren
  '/products/$subdomain': typeof ProductsSubdomainRoute
  '/admin/': typeof AdminIndexRoute
  '/p/$subdomain/$country': typeof PSubdomainCountryRoute
  '/p/$subdomain/': typeof PSubdomainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/thank-you'
    | '/track'
    | '/upsell'
    | '/admin/countries'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/domains'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subdomains'
    | '/p/$subdomain'
    | '/products/$subdomain'
    | '/admin/'
    | '/p/$subdomain/$country'
    | '/p/$subdomain/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/thank-you'
    | '/track'
    | '/upsell'
    | '/admin/countries'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/domains'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subdomains'
    | '/products/$subdomain'
    | '/admin'
    | '/p/$subdomain/$country'
    | '/p/$subdomain'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/thank-you'
    | '/track'
    | '/upsell'
    | '/admin/countries'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/domains'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subdomains'
    | '/p/$subdomain'
    | '/products/$subdomain'
    | '/admin/'
    | '/p/$subdomain/$country'
    | '/p/$subdomain/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TrackRoute: typeof TrackRoute
  UpsellRoute: typeof UpsellRoute
  PSubdomainRoute: typeof PSubdomainRouteWithChildren
  ProductsSubdomainRoute: typeof ProductsSubdomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$subdomain': {
      id: '/products/$subdomain'
      path: '/products/$subdomain'
      fullPath: '/products/$subdomain'
      preLoaderRoute: typeof ProductsSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$subdomain': {
      id: '/p/$subdomain'
      path: '/p/$subdomain'
      fullPath: '/p/$subdomain'
      preLoaderRoute: typeof PSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subdomains': {
      id: '/admin/subdomains'
      path: '/subdomains'
      fullPath: '/admin/subdomains'
      preLoaderRoute: typeof AdminSubdomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/countries': {
      id: '/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$subdomain/': {
      id: '/p/$subdomain/'
      path: '/'
      fullPath: '/p/$subdomain/'
      preLoaderRoute: typeof PSubdomainIndexRouteImport
      parentRoute: typeof PSubdomainRoute
    }
    '/p/$subdomain/$country': {
      id: '/p/$subdomain/$country'
      path: '/$country'
      fullPath: '/p/$subdomain/$country'
      preLoaderRoute: typeof PSubdomainCountryRouteImport
      parentRoute: typeof PSubdomainRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCountriesRoute: typeof AdminCountriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubdomainsRoute: typeof AdminSubdomainsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCountriesRoute: AdminCountriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubdomainsRoute: AdminSubdomainsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PSubdomainRouteChildren {
  PSubdomainCountryRoute: typeof PSubdomainCountryRoute
  PSubdomainIndexRoute: typeof PSubdomainIndexRoute
}

const PSubdomainRouteChildren: PSubdomainRouteChildren = {
  PSubdomainCountryRoute: PSubdomainCountryRoute,
  PSubdomainIndexRoute: PSubdomainIndexRoute,
}

const PSubdomainRouteWithChildren = PSubdomainRoute._addFileChildren(
  PSubdomainRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TrackRoute: TrackRoute,
  UpsellRoute: UpsellRoute,
  PSubdomainRoute: PSubdomainRouteWithChildren,
  ProductsSubdomainRoute: ProductsSubdomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
